### ISSUE TITLE
Can't login on Kibana with Searchguard

### ISSUE THREAD

**Issue by cooperspencer** [floragunncom/search-guard-kibana-plugin#25]
Hi,

When I try to enter kibana I always get:
An error occurred while checking your credentials, make sure your have a running Elasticsearch cluster secured by Search Guard running.

I attached my configfiles. Maybe I forgot something in the config.

[kibana.txt](https://github.com/floragunncom/search-guard-kibana-plugin/files/1063361/kibana.txt)
[elastic.txt](https://github.com/floragunncom/search-guard-kibana-plugin/files/1063363/elastic.txt)

**Comment by jochenkressin** [comment]
The error message you are seeing is displayed when the "authinfo" endpoint, which is provided by SG and used to validate the users credentials, is not accessible.

Are ES and KI running on the same machine? I guess so since your elasticsearch.url is set to 

elasticsearch.url: "https://localhost:9200"

What happens when you try to access this endpoint directly?

https://localhost:9200/_searchguard/authinfo

**Comment by cooperspencer** [comment]
I get a json.
But I entered it from my webbrowser. ES and KI are running on an virtual machine without GUI

{"user":"User [name=admin, roles=[]]","user_name":"admin","user_requested_tenant":null,"remote_address":"-------------","sg_roles":["sg_all_access","sg_own_index","sg_public"],"sg_tenants":{"test_tenant_ro":true,"admin":true,"adm_tenant":true},"principal":null,"peer_certificates":"0"}

**Comment by jochenkressin** [comment]
Strange. Do you see anything in the ES or KI log file?

**Comment by cooperspencer** [comment]
[2017-06-19T14:09:06,256][WARN ][c.f.s.h.SearchGuardHttpServerTransport] [---------] Someone (/127.0.0.1:60655) speaks http plaintext instead of ssl, will close the channel

I see that in the elasticsearch log.

**Comment by cooperspencer** [comment]
and that
[2017-06-19T13:58:02,447][INFO ][c.f.s.a.BackendRegistry  ] Cannot authenticate user (or add roles) with ad 4 due to ElasticsearchSecurityException[com.google.common.util.concurrent.UncheckedExecutionException: ElasticsearchSecurityException[kibanaadmin not found]]; nested: UncheckedExecutionException[ElasticsearchSecurityException[kibanaadmin not found]]; nested: ElasticsearchSecurityException[kibanaadmin not found];, try next

**Comment by jochenkressin** [comment]
Something is strange here. This one:

[2017-06-19T14:09:06,256][WARN ][c.f.s.h.SearchGuardHttpServerTransport] [---------] Someone (/127.0.0.1:60655) speaks http plaintext instead of ssl, will close the channel

means that someone, e.g. Kibana or browser, tried to access ES with HTTP instead of HTTPS.

But on your kibana.yml you have

elasticsearch.url: "https://localhost:9200"

So, can you please do the following:
- Stop ES and KI and delete all log files from ES and KI
- Set the Search Guard log level to debug. In config/log4j2.properties, set:

logger.fg.name = com.floragunn
logger.fg.level = debug

- Start ES and KI
- Access KI and try to log in (I guess you use "kibanaadmin" as login?
- Stop ES and KI

And then send us the ES and KI logfiles and the complete SG configuration files.

**Comment by cooperspencer** [comment]
Actually I tried it with kibanaserver. I have no idea where the kibanaadmin came from.

**Comment by cooperspencer** [comment]
Is it ok to send it by email?

**Comment by jochenkressin** [comment]
sure, you can use info@floragunn.com!

**Comment by cooperspencer** [comment]
Thanks a lot.

**Comment by floragunncom** [comment]
@cooperspencer does the issue still persist?

**Comment by floragunncom** [comment]
no feedback, assume solved

**Comment by yabir** [comment]
So... what was the solution? i have the same problem and the documentation is so complex

**Comment by cooperspencer** [comment]
Sorry, didn't found one and gave up.

**Comment by RodKWATE** [comment]
I have the same problem

**Comment by RodKWATE** [comment]
anny issue ?
