### ISSUE TITLE
Visibility of index names in dropdown should be based on access permissions to them

### ISSUE THREAD

**Issue by alesnav** [floragunncom/search-guard-kibana-plugin#6]
Hello there!

It would be nice if the dropdown that shows the Elasticsearch indices depended on the user permissions for each one.

For example, if user A have access to the index B, it should be shown in the dropdown. But, if user C lacks access to that index, it should be hidden from the dropdown.

This way, it would be possible to use Search Guard Kibana plugin in a SIEM-as-a-service tool because one customer would only see his own data and every other data (including the index name) wouldn't be visible for him.

Thanks,
Best regards

**Comment by floragunncom** [comment]
That's not easily possible, due to the way Kibana works. Kibana does not have any multi-tenancy capabilities built in, but uses one global user (the one you configure in kibana.yml) to issue those types of queries. That's also why all users share the same dashboards and visualizations. We're working on an Search Guard Kibana module at the moment, which will in a first step provide separation of dashboards and visualizations based on a users role(s).

**Comment by alesnav** [comment]
Thanks @floragunncom .

I will try to be patient :wink:

BTW, do you have any public roadmap?

Best regards!

**Comment by xycloud** [comment]
cool, i can already see the config item 'multi-tenancy' in search-guard-kibana-plugin

**Comment by floragunncom** [comment]
Not at the moment, since requirements from customers and users are changing fast. However, we think about setting up a voting tool on our website, so you can submit new feature requests and upvote existing ones.

**Comment by alesnav** [comment]
Hello,

I think that this issue should be closed since you have published the new 5.3.0 version, which includes this enhancement (using tenants).

Thanks!!!
